/// <reference types="vite/client" />

import { initializeApp, getApps, getApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getStorage } from 'firebase/storage';
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut as firebaseSignOut } from 'firebase/auth';
import type { FirebaseOptions } from 'firebase/app';

// Local config
import localConfigRaw from '../../firebase-applet-config.json';
const localConfig = localConfigRaw as Record<string, any>;

// Load config. In Vercel, prefer process.env/import.meta.env.
// Fallback to local config generated by the dev environment.
const loadConfig = (): FirebaseOptions => {
  return {
    projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || localConfig.projectId,
    appId: import.meta.env.VITE_FIREBASE_APP_ID || localConfig.appId,
    apiKey: import.meta.env.VITE_FIREBASE_API_KEY || localConfig.apiKey,
    authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || localConfig.authDomain,
    storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || localConfig.storageBucket,
    messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || localConfig.messagingSenderId,
    measurementId: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID || localConfig.measurementId,
  };
};

const firebaseConfig = loadConfig();

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();

let db;
try {
  // Use the firestoreDatabaseId from config if it exists
  const dbId = import.meta.env.VITE_FIREBASE_DATABASE_ID || localConfig.firestoreDatabaseId;
  db = getFirestore(app, dbId);
} catch (e) {
  db = getFirestore(app);
}

export { db };
export const storage = getStorage(app);
export const auth = getAuth(app);
export const googleProvider = new GoogleAuthProvider();

export const loginWithGoogle = async () => {
  try {
    const result = await signInWithPopup(auth, googleProvider);
    return result.user;
  } catch (error) {
    console.error("Error signing in with Google", error);
    throw error;
  }
};

export const logout = async () => {
  try {
    await firebaseSignOut(auth);
  } catch (error) {
    console.error("Error signing out", error);
    throw error;
  }
};
